// Must use arrow function syntax in Mintlify snippets
export const InstallExtension = ({ source, environment, schemaUrl }) => {
  return (
    <>
      <p>
        The {source} extension includes a schema that tells BloodHound how to model and analyze data from your {source} {environment}. You must install the extension before you upload data generated by a collector.
      </p>

      <ul>
        <li>
          <strong>BloodHound Community</strong>: Download the latest {source} <a href={schemaUrl} target="_blank" rel="noopener noreferrer">extension definition schema</a> file from the OpenHound GitHub repository and install it on the <a href="/opengraph/extensions/manage">OpenGraph Management</a> page in BloodHound.
        </li>
        <li>
          <strong>BloodHound Enterprise</strong>: Contact your account team to get the enterprise version of the schema installed, including BloodHound Enterprise findings.
        </li>
      </ul>

      <p>
        After the extension is installed, BloodHound is ready to ingest and analyze {source} data.
      </p>
    </>
  );
};

export default InstallExtension;
