// Must use arrow function syntax in Mintlify snippets
export const InstallExtension = ({
  source,
  environment,
  schemaUrl,
  enterpriseEmbedded = false,
  enterpriseEmbeddedVersion = 'v9.3.0',
}) => {
  return (
    <>
      <p>
        The {source} extension includes a schema that tells BloodHound how to model and analyze data from your {source} {environment}. Make sure the schema is installed before you upload data generated by a collector.
      </p>

      <ul>
        <li>
          <strong>BloodHound Community</strong>: Download the latest {source} <a href={schemaUrl} target="_blank" rel="noopener noreferrer">extension definition schema</a> file from the OpenHound GitHub repository and install it on the <a href="/opengraph/extensions/manage">OpenGraph Management</a> page in BloodHound.
        </li>
        <li>
          <strong>BloodHound Enterprise</strong>:{' '}
          {enterpriseEmbedded ? (
            <>
              In BloodHound Enterprise {enterpriseEmbeddedVersion} and later, {source} is supported as a pre-installed extension. Use the <a href="/opengraph/extensions/manage">OpenGraph Management</a> page to verify the installed version or update to a newer version manually outside the standard BloodHound Enterprise release cycle.
            </>
          ) : (
            <>
              Upload the schema on the <a href="/opengraph/extensions/manage">OpenGraph Management</a> page before you ingest data for this extension.
            </>
          )}
        </li>
      </ul>

      <p>
        After the extension is installed, BloodHound is ready to ingest and analyze {source} data.
      </p>
    </>
  );
};

export default InstallExtension;
